name: Enterprise CI/CD Pipeline

on:
  push:
    branches: ["main", "stage", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with: { version: 9 }

      - uses: actions/setup-node@v4
        with: { node-version: 22, cache: "pnpm" }

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Unit Tests
        run: pnpm run test

      - name: Build
        run: |
          npx tsc --noEmit
          pnpm run build

      - name: Save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: ./dist

  # CD
  deploy-dev:
    needs: build
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with: { name: dist-folder, path: ./dist }
      - name: Simulate DEV Deploy
        run: |
          echo " send  AWS S3:"
          ls -la ./dist

  deploy-stage:
    needs: build
    if: github.ref == 'refs/heads/stage'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with: { name: dist-folder, path: ./dist }
      - name: Simulate STAGING Deploy
        run: echo "Simulating STAGING Deploy"

  deploy-prod:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with: { name: dist-folder, path: ./dist }

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
